# Generated by Django 5.0.2 on 2024-02-29 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='groups',
        ),
    ]
